title: anaphors
url: https://stokes.io
jekyll_compose:
  default_front_matter:
    posts:
      layout: post
exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - flake.nix
  - flake.lock
  - README.md
  - vendor
  - AGENTS.md
  - CLAUDE.md
